export enum ObjectTypes {
    CONNECTED_SYSTEM = 'connected_system',
    CONSTANT = 'constant',
    DATA_STORE = 'data_store',
    DATA_TYPE = 'data_type',
    DECISION = 'decision',
    DOCUMENT = 'document',
    EXPRESSION_RULE = 'rule',
    FEED = 'feed',
    FOLDER = 'folder',
    GROUP = 'group',
    INTEGRATION = 'integration',
    INTERFACE = 'rule',
    PROCESS_MODEL = 'process_model',
    QUERY_RULE = 'query_rule',
    RECORD_TYPE = 'record_type',
    REPORT = 'report',
    SITE = 'site',
    WEB_API = 'WEB_API',
}